# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20160328_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to=settings.MEDIA_ROOT)),
            ],
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Image')),
            ],
        ),
        migrations.CreateModel(
            name='SliderItemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('sliderItem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.SliderItem')),
            ],
        ),
    ]
